//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciaRH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GerenciaRH.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível acessar avaliação, contate um administrador com o erro.
        /// </summary>
        public static string mensagemErroAcessoAvaliacao {
            get {
                return ResourceManager.GetString("mensagemErroAcessoAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante processo de avaliação, contate um administrador ou tente novamente.
        /// </summary>
        public static string mensagemErroAvaliacao {
            get {
                return ResourceManager.GetString("mensagemErroAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao efetuar login, sem conexão à base.
        /// </summary>
        public static string mensagemErroBase {
            get {
                return ResourceManager.GetString("mensagemErroBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante desligamento, contate um administrador ou tente novamente.
        /// </summary>
        public static string mensagemErroDesligamento {
            get {
                return ResourceManager.GetString("mensagemErroDesligamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no login, verificar usuário/senha.
        /// </summary>
        public static string mensagemErroLogin {
            get {
                return ResourceManager.GetString("mensagemErroLogin", resourceCulture);
            }
        }
    }
}
